// Generated by Wrangler on Sun Aug 04 2024 17:17:31 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	AUTH_KEY: "AUTH KEY";
	APPLICATION_AUTH_KEY: "AUTH KEY";
	TOKEN_EXPIRY_TIME: "1h";
	SERVER_JWK: string;
	DB: D1Database;
	USER_AUTH: Fetcher;
}
