// Generated by Wrangler on Sun Aug 04 2024 10:05:40 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	AUTH_KEY: "AUTH KEY";
	JWT_SIGNATURE: string;
	DB: D1Database;
	USER_AUTH: Fetcher;
}
