// Generated by Wrangler on Thu Aug 08 2024 13:06:41 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types`

interface Env {
	AUTH_KEY: "AUTH KEY";
	APPLICATION_AUTH_KEY: "APPLICATION AUTH KEY";
	TOKEN_EXPIRY_TIME: 3600;
	JWT_EXPORY_TIME: "1h";
	SERVER_JWK: string;
	USER_ID_AUTH_KEY: string;
	USER_DATA_AUTH_KEY: string;
	DB: D1Database;
	USER_AUTH: Fetcher;
	USER_DATA: Fetcher;
}
